### ISSUE TITLE
Error: A branch named ... already exists

### ISSUE THREAD

**Issue by jdemeyer** [sagemath/git-trac-command#24]
This sometimes happens:
```
$ git trac checkout 19525
Loading ticket #19525...
Newly created local branch: t/19525/improve_glpk_error_handling
Traceback (most recent call last):
  File "/home/jdemeyer/local/bin/git-trac", line 18, in <module>
    cmdline.launch()
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/cmdline.py", line 209, in launch
    app.checkout(args.ticket_or_branch, args.branch_name)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/app.py", line 115, in checkout
    self._checkout_ticket(int(ticket_or_branch), branch_name)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/app.py", line 129, in _checkout_ticket
    self.repo.create(local)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_repository.py", line 133, in create
    self.git.branch(local, 'FETCH_HEAD')
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 341, in meth
    return self.execute(git_cmd, *args, **kwds)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 328, in execute
    popen_stderr=subprocess.PIPE)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 263, in _run
    raise GitError(result)
git_trac.git_error.GitError: git returned with non-zero exit code (128) when executing "git branch t/19525/improve_glpk_error_handling FETCH_HEAD"
    STDERR: fatal: A branch named 't/19525/improve_glpk_error_handling' already exists.
```

In this case, `git trac checkout 19525` should just checkout the already-existing branch.

**Comment by vbraun** [comment]
This should work; Do you have the latest version of git-trac-command?
~~~~
$ git trac checkout 19470
Loading ticket #19470...
Checking out Trac #19470 remote branch u/vbraun/easier_package_update -> local branch t/19470/easier_package_update...
Local branch already exists. Use "git trac pull" to get updates.
~~~~

**Comment by jdemeyer** [comment]
I was using bd1b81e6e34d46c8cedb281c6d8d81487f99e7d0 which is 3 commits away from master. I upgraded now, I'll let you know if it happens again.

**Comment by jdemeyer** [comment]
Again with 8ee7ee7fe57a4afc593446e266e5b8f52c374969:
```
$ git trac checkout 12482
Loading ticket #12482...
Newly created local branch: t/12482/isinstance_failure_on_lazy_imported_class
Traceback (most recent call last):
  File "/home/jdemeyer/local/bin/git-trac", line 18, in <module>
    cmdline.launch()
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/cmdline.py", line 209, in launch
    app.checkout(args.ticket_or_branch, args.branch_name)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/app.py", line 115, in checkout
    self._checkout_ticket(int(ticket_or_branch), branch_name)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/app.py", line 129, in _checkout_ticket
    self.repo.create(local)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_repository.py", line 133, in create
    self.git.branch(local, 'FETCH_HEAD')
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 341, in meth
    return self.execute(git_cmd, *args, **kwds)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 328, in execute
    popen_stderr=subprocess.PIPE)
  File "/home/jdemeyer/local/src/git-trac-command/git_trac/git_interface.py", line 263, in _run                                                                         
    raise GitError(result)                                                                                                                                              
git_trac.git_error.GitError: git returned with non-zero exit code (128) when executing "git branch t/12482/isinstance_failure_on_lazy_imported_class FETCH_HEAD"        
    STDERR: fatal: A branch named 't/12482/isinstance_failure_on_lazy_imported_class' already exists.                                                                   
```

**Comment by vbraun** [comment]
I guess this happens only if there is no branch on the ticket, thats why I couldn't reproduce it
