### ISSUE TITLE
Git-trac mangles Git's error message when it contains non-ascii characters

### ISSUE THREAD

**Issue by jsrndk** [sagemath/git-trac-command#25]
With non-english localization, git-trac seems not to appreciate Git's error messages, and instead of informing the user what Git originally raised, a `str() error` is printed instead.

We  observed this on a french machine (at SageDays75). I have english localization on my machine and my initial tries at getting Git to print french on my machine failed, so I can't reproduce it. But I thought it worth reporting anyway.

**Comment by vbraun** [comment]
Traceback would be nice...

**Comment by jsrndk** [comment]
I can't reproduce it on my own machine it seems: `LANGUAGE=fr_FR.UTF-8 git trac ..." gives me a french Git, but I haven't been able to make it give that error. I'll try to contact one of the people at SD75 who had this error.

**Comment by jsrndk** [comment]
Julien Lavauzelle gave me the traceback of the error he had at the time. He doesn't know how to reproduce it without pushing random stuff to tickets.

```
Pushing to Trac #20100...
Guessed remote branch: u/jlavauzelle/cyclic_code
Traceback (most recent call last):
File "/usr/local/bin/git-trac", line 18, in <module>
cmdline.launch()
File "/usr/local/lib/python2.7/dist-packages/git_trac/cmdline.py", line 223, in
launch
app.push(ticket_number, remote=args.remote, force=args.force)
File "/usr/local/lib/python2.7/dist-packages/git_trac/app.py", line 216, in push
self.repo.push(remote, force)
File "/usr/local/lib/python2.7/dist-packages/git_trac/git_repository.py", line
197, in push
self.git.echo.push('trac', refspec)
File "/usr/local/lib/python2.7/dist-packages/git_trac/git_interface.py", line
341, in meth
return self.execute(git_cmd, *args, **kwds)
File "/usr/local/lib/python2.7/dist-packages/git_trac/git_interface.py", line
98, in execute
popen_stderr=subprocess.PIPE)
File "/usr/local/lib/python2.7/dist-packages/git_trac/git_interface.py", line
263, in _run
raise GitError(result)
git_trac.git_error.GitError: <exception str() failed>
```

The error was resolved when Julien switched remote from `git://...` to `git@...`. When running the pure Git command without `git-trac`, we got a more understandable error message.
