### ISSUE TITLE
SSL Certificate verfication failed while configuring git and trac

### ISSUE THREAD

**Issue by diveshkr-code** [sagemath/git-trac-command#47]
While configuring git and trac through guidelines given here [docs.sagemath](http://doc.sagemath.org/html/en/developer/trac.html)
`git trac config --user USERNAME --pass 'PASSWORD'` gives as error

> 
> Saved trac username.
> Saved trac password.
> Trac xmlrpc URL:
>     https://trac.sagemath.org/xmlrpc (anonymous)
>     https://trac.sagemath.org/login/xmlrpc (authenticated)
>     realm sage.math.washington.edu
> Username: diveshkr-code
> Password: ***********
> Retrieving SSH keys...
> Traceback (most recent call last):
>   File "/home/diveshcode/git-trac-command/bin/git-trac", line 17, in <module>
>     cmdline.launch()
>   File "/home/diveshcode/git-trac-command/git_trac/cmdline.py", line 284, in launch
>     app.print_config()
>   File "/home/diveshcode/git-trac-command/git_trac/app.py", line 391, in print_config
>     for key in self.trac.get_ssh_fingerprints():
>   File "/home/diveshcode/git-trac-command/git_trac/trac_server.py", line 111, in get_ssh_fingerprints
>     for key in self.get_ssh_keys():
>   File "/home/diveshcode/git-trac-command/git_trac/trac_server.py", line 103, in get_ssh_keys
>     return self.authenticated_proxy.sshkeys.getkeys()
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/home/diveshcode/git-trac-command/git_trac/digest_transport_py2.py", line 127, in single_request
>     response = self.opener.open(req)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
>     context=self._context)
>   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by georgiachanning** [comment]
@diveshkr-code Did you ever figure this out? Running into the same issue. I was able to solve the issue by enabling my conda environment (which I usually disable when working with Sage because it gives me compilation issues). Unsure about what it changed.
